### PR TITLE
Resolved following JIRAs

### PR DESCRIPTION
**Pull request by Jiten-Patel**
[JIRA] (CE-61)
[JIRA] (CE-65)
[JIRA] (CE-66)
[JIRA] (CE-67)

### CODE REVIEW

**Comment by BoundedBuffer** [comment]
thanks

**Comment by BoundedBuffer** [comment]
sorry I didn't merge the changes before closing.. so re opening

**Comment by BoundedBuffer** [comment]
thank merged

**Comment by Jiten-Patel** [comment]
Hi Rob,
Thanks.

For commit message, while still writing message, I have clicked Enter key
by mistake.
Next time I will take care about it.

--
Regards,
Jiten

**Pull request closed without merging**
